name: TinyWiFiAnalyzer
options:
  bundleIdPrefix: io.github.nolze
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    GENERATE_INFOPLIST_FILE: YES

targets:
  TinyWiFiAnalyzer:
    type: application
    platform: macOS
    sources:
      - Sources/TinyWiFiAnalyzer
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.github.nolze.tiny-wifi-analyzer
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "On macOS 14 Sonoma and Later, Location Services permission is required to get Wi-Fi SSIDs. Please enable Location Services in System Preferences > Security & Privacy > Privacy > Location Services."
        INFOPLIST_KEY_LSMinimumSystemVersion: "14.0"
        INFOPLIST_KEY_NSPrincipalClass: NSApplication
    dependencies:
      - sdk: CoreWLAN.framework
      - sdk: CoreLocation.framework
  TinyWiFiAnalyzerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - Tests/TinyWiFiAnalyzerTests
    dependencies:
      - target: TinyWiFiAnalyzer
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
